### PR TITLE
Tungsten and Damascus Steel Line

### PR DESCRIPTION
**Pull request by jude123412**
Added Damascus Steel Line
Added files for all items that don't have them
Added Damascus Steel Line Meta Items
Fixed Tungsten Line Recipe
Fixed Bituminous Residues and Paraffin Wax Textures and Names

### CODE REVIEW

**Review by tekcay — APPROVED** [review]
Everything works as intended. Don't you want to add the textures for the damascus steel items ? That'd complete properly  this PR content :)

**Comment by jude123412** [comment]
yes! just finished adding them 👍

**Comment by jude123412** [comment]
All textures now ready

**Review by tekcay — COMMENTED** [review]
noice :)

**Pull request merged**
