### PR TITLE
Material Icon Sets, Damascus Steel Line Finish and Finally Damascus Steel Icon Sets

### PR DESCRIPTION
**Pull request by jude123412**
Added Class Files for Material Icon Set Creation along with Damascus Icon Sets Added Textures for all Damascus Icon Sets
Added Chemical Formula for Damascus Steel
Finished Damascus Steel Line, Now produces Ingots instead of Plates
Changes to various code to make it more clean

### CODE REVIEW

**Comment by BLocky104** [comment]
did you test stuff ingame yet, like recipes and stuff?

**Review by tekcay — APPROVED** [review]

**Comment by jude123412** [comment]
Yes, All tested in current branch :)

**Review by BLocky104 — APPROVED** [review]
ready for merge I suppose

**Comment by jude123412** [comment]
good good, 👍

**Pull request merged**
